name: On push into Master
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build and Publish Fresh Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Push to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ayase252/rq-scheduler-docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
